version: "3"

services:
  mongo:
    restart: unless-stopped
    image: mongo:5
    ports:
      - 27017:27017
    volumes:
      - 'mongo_data:/data/db'

  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379

  minio:
    restart: unless-stopped
    image: 'minio/minio'
    command: ['server', '/data', '--console-address', ':9001']
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - 'minio_data:/data'

  mc:
    image: 'minio/mc'
    volumes:
      - './mc/entrypoint.sh:/fig/entrypoint.sh'
    entrypoint: '/fig/entrypoint.sh'
    depends_on:
      - minio

  rabbitmq:
    image: rabbitmq:3.8
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  minio_data:
  mongo_data:

