version: "3"

services:
  mongo:
    image: mongo:4.4
    ports:
      - 27017:27017
    env_file:
      - .env

  # webapi:
  #     build:
  #         context: ./webapi
  #     volumes: 
  #         - .:/server
  #     ports:
  #         - 8080:8080
  
  # profilesvc:
  #     build:
  #         context: ./profilesvc
  #     volumes: 
  #         - .:/server
  #     ports:
  #         - 50051:50051

  # api-gateway:
  #     image: nginx:latest
  #     restart: unless-stopped
  #     volumes:
  #         - ./api-gateway/nginx.conf:/etc/nginx/nginx.conf
  #         - ./api-gateway/localhost.crt:/etc/nginx/localhost.crt
  #         - ./api-gateway/localhost.key:/etc/nginx/localhost.key
  #     ports:
  #         - 80:80
  #         - 443:443

  # client:
  #     build:
  #         context: ./client
  #     volumes: 
  #         - /app/node_modules
  #         - ./client:/app
  #     ports:
  #         - 8080:8080
  #     env_file:
  #         - ./client/.env
  #     stdin_open: true

  # auth:
  #     build:
  #         context: ./auth
  #     volumes:
  #         - /app/node_modules
  #         - ./auth:/app
  #     env_file:
  #         - ./auth/.env

  # api:
  #     build:
  #         context: ./server
  #         target: dev
  #     env_file:
  #         - ./server/.env
  #     volumes:
  #         - /app/node_modules
  #         - ./server:/app

  # seed:
  #     build:
  #         context: ./seed
  #     volumes:
  #         - ./seed/output_data:/seed/output_data
  #     depends_on:
  #         - db

