version: "2"
services:
    feed-api:
        build:
            context: ./feed
        ports: 
            - 5001:5001
        volumes:
            - /app/node_modules
            - ./feed:/app
    client:
        build:
            context: ./client
        ports:
            - 3000:3000
        volumes: 
            - /app/node_modules
            - ./client:/app
        stdin_open: true
