version: "2"
services:

    client:
        build:
            context: ./client
        ports:
            - 3000:3000
        volumes: 
            - /app/node_modules
            - ./client:/app
        stdin_open: true
    
    db:
        image: mongo:4.4
        ports:
            - 27017:27017

    seed:
        image: mongo:4.4
        volumes:
            - ./seed:/seed
        command: 
            - /seed/seed.sh
        depends_on:
            - db
        

    api:
        build:
            context: ./server
        ports: 
            - 5001:5001
        volumes:
            - /app/node_modules
            - ./server:/app
        depends_on:
            - seed
