version: "2"
services:
    reverse-proxy:
        image: nginx:latest
        volumes:
            - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 80:80
            - 443:443
        depends_on:
            - api
            - client

    client:
        build:
            context: ./client
        ports:
            - 3000:3000
        volumes: 
            - /app/node_modules
            - ./client:/app
        stdin_open: true

    api:
        build:
            context: ./server
        ports: 
            - 5001:5001
        volumes:
            - /app/node_modules
            - ./server:/app
        depends_on:
            - seed

    db:
        image: mongo:4.4
        ports:
            - 27017:27017

    seed:
        image: mongo:4.4
        volumes:
            - ./seed:/seed
        command: 
            - /seed/seed.sh
        depends_on:
            - db
