version: "3"

services:
  mongo:
    restart: unless-stopped
    image: mongo:4.4
    ports:
      - 27017:27017
    env_file:
      - .env

  webapi:
    build:
      context: .
    ports:
      - 8080:8080
    volumes:
      - .:/fig
    env_file:
      - .env
    command: [ "go", "run", "/fig/cmd/webapi/main.go" ]

  
  profilesvc:
    build:
      context: .
    ports:
      - 50051:50051
    volumes:
      - .:/fig
    env_file:
      - .env
    depends_on: 
      - mongo
    command: [ "go", "run", "/fig/cmd/profilesvc/main.go" ]

  # auth:
  #     build:
  #         context: ./auth
  #     volumes:
  #         - /app/node_modules
  #         - ./auth:/app
  #     env_file:
  #         - ./auth/.env

