version: "3"

services:
  mongo:
    restart: unless-stopped
    image: mongo:5
    ports:
      - 27017:27017

  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379

  minio:
    restart: unless-stopped
    image: "minio/minio"
    command: ["server", "/data"]
    environment:
      MINIO_ACCESS_KEY: MINIO_ACCESS_KEY
      MINIO_SECRET_KEY: MINIO_SECRET_KEY
    ports:
      - 9000:9000
    volumes:
      - "minio_data:/data"

volumes:
  minio_data:
