version: "3"

services:
  mongo:
    restart: unless-stopped
    image: mongo:4.4
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379

