import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Fig</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        Place holder for main page
        <h1><Link href="/login">/login</Link></h1>
        <h1><Link href="/profile">/profile</Link></h1>
      </main>

    </div>
  )
}

export default Home
