// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewProfile struct {
	Name     string `json:"name"`
	Username string `json:"username"`
	Email    string `json:"email"`
}

type Profile struct {
	Name     string `json:"name"`
	Username string `json:"username"`
	Summary  string `json:"summary"`
	Email    string `json:"email"`
}
